### ISSUE TITLE
GetTransactionsExample.java broken

### ISSUE THREAD

**Issue by alexprut** [ketola/jlibra#90] opened 2020-01-21 19:47 UTC
The provided example: https://github.com/ketola/jlibra/blob/master/jlibra-examples/src/main/java/dev/jlibra/example/GetTransactionsExample.java is broken.
The returning error is: `Only Script payload is supported` (i.e. from `Transaction` class)

btw, nice project ;)

**Comment by ketola** [comment] 2020-01-22 18:53
Yes, It seems the transaction de-serialization is broken. Thanks for reporting!

**Comment by ketola** [comment] 2020-01-22 20:19
I did some testing and noticed that the query works with parameters (this returns a normal p2p transaction):
``
long start = 14980115;
long limit = 1;
``
The one that caused the exception was version number: 8720763 which seems to be a "block metadata" type of transaction: http://explorer.moveonlibra.com/transactions/8720763
I guess that would need to be serialized in a different way.

As a first step I could change the parameters in the example to working ones but jlibra would also need support for deserializing that transaction type.

**Comment by ketola** [comment] 2020-01-23 16:49
Here's some more information for this:

The Transaction enum is declared here: https://github.com/libra/libra/blob/master/types/src/transaction/mod.rs#L1062
- based on that I assume that we can detect the normal Transaction from prefix = 0 and the BlockMetadata should be 2. (now we just ignore it here: https://github.com/ketola/jlibra/blob/master/jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/Transaction.java#L51)

The block metadata is explained in this file: https://github.com/libra/libra/blob/master/types/src/block_metadata.rs
- the fields to be de-serialized can be seen here

The de-serialization of a map can be found here in the lcs documentation: https://github.com/libra/libra/blob/master/common/lcs/src/lib.rs 

I guess the contents of the BlockMetadata are irrelevant in most use cases so the minimum would be to detect the block metadata without causing an error and maybe just have a placeholder object for it, but it also might be pretty straightforward to de-serialize properly.

**Comment by alexprut** [comment] 2020-01-23 20:19
It's quite sad that the proto for a transaction is:
```
// A generic structure that represents a transaction, covering all possible
// variants.
message Transaction { bytes transaction = 1; }
```
How did you figure out how to parse the bytes? (i.e. https://github.com/ketola/jlibra/blob/master/jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/Transaction.java#L47)

**Comment by ketola** [comment] 2020-01-24 06:14
> It's quite sad that the proto for a transaction is just a bunch of bytes ...:
> 
> ```
> // A generic structure that represents a transaction, covering all possible
> // variants.
> message Transaction { bytes transaction = 1; }
> ```
> 
Yes, it was not like this in the beginning when the api was released. Originally the grpc classes had proper fields for each attribute and the api was easier to use, but they later introduced the "libra canonical serialization" (you can read the specs here: https://github.com/libra/libra/blob/master/common/lcs/src/lib.rs) and the reasons for the change here: https://github.com/libra/libra/issues/454

> How did you figure out how to parse the bytes? (i.e. https://github.com/ketola/jlibra/blob/master/jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/Transaction.java#L47)

The "libra canonical serialization" defines rules for serializing the data structures, so it's based on that. I don't like it very much as it makes the libra api expose the internals of libra, meaning that I need to check the source code of Libra every time I want to serialize/de-serialize something and this also causes errors in the client because the changes in these data structures are not visible in the api.

**Comment by alexprut** [comment] 2020-01-24 13:57
This seems a little bit complex :D
thanks @ketola

**Comment by ketola** [comment] 2020-04-18 10:21
A small update on this: I think this issue will be solved once the json-rpc integration is merged to master. I'm still waiting for libra project to confirm that the grpc api will be discontinued, until that I don't want to do any updates to the grpc integration.

**Comment by alexprut** [comment] 2020-04-21 08:41
Thanks for the update, I've missed this shift from Libra, are you referencing this PR: https://github.com/libra/libra/pull/3520 ?

`grpc api will be discontinued` do you know where I can find that discussion? 🙏

**Comment by ketola** [comment] 2020-04-21 09:32
Libra has published a json-rpc api, jlibra has a branch (https://github.com/ketola/jlibra/tree/jsonrpc) where the integration has been developed. I asked over a month ago about it in the community forum: https://community.libra.org/t/json-rpc/2618 but I'm still waiting for the blog post that was promised as a response.
I'm guessing they will drop the grpc api because the reference client is using the json-rpc api only, but I would like to have it confirmed before removing the code from jlibra.

**Comment by ketola** [comment] 2020-05-01 08:39
Ok, the json rpc api is now in master. I decided to go ahead and remove the grpc code, even though the dropping of grpc api has not been confirmed, but it sure looks like it will be dropped based on the activity in the libra rep.

**Closed by ketola** 2020-05-01 08:39 UTC
